CB_ALL 	= 0;
CB_IC	= 1;
CB_OOC 	= 2;

CC_CREATE 			= 0;
CC_CREATESELECT 	= 1;
CC_CREATESELECT_C 	= 2;
CC_SELECT 			= 3;
CC_SELECT_C 		= 4;

IRON_HOLSTERED 		= 0;
IRON_HOLSTERED2IDLE = 1;
IRON_IDLE 			= 2;
IRON_IDLE2AIM 		= 3;
IRON_AIM 			= 4;

SONG_IDLE 		= 0;
SONG_ALERT 		= 1;
SONG_ACTION 	= 2;
SONG_STINGER 	= 3;

DOOR_UNBUYABLE			= 0;
DOOR_BUYABLE 			= 1;
DOOR_COMBINEOPEN 		= 2;
DOOR_COMBINELOCK 		= 3;
DOOR_BUYABLE_ASSIGNABLE = 4;

LICENSE_FOOD 		= 2^0;
LICENSE_ALCOHOL 	= 2^1;
LICENSE_ELECTRONICS = 2^2;
LICENSE_MISC 		= 2^3;
LICENSE_BLACK 		= 2^4;

CPAPP_NONE 			= 0;
CPAPP_APPLIED 		= 1;
CPAPP_DENIED 		= 2;
CPAPP_DENIED_DONE 	= 3;
CPAPP_SUCC 			= 4;
CPAPP_SUCC_DONE 	= 5;

NEWBIE_STATUS_NEW = 0;
NEWBIE_STATUS_OLD = 1;

TRAIT_NONE 		= 2^0;
TRAIT_CONDUCTOR = 2^1;
TRAIT_ROCKY 	= 2^2;
TRAIT_LOYALIST 	= 2^3;
TRAIT_GLUTTON 	= 2^4;
TRAIT_LUCKY 	= 2^5;
TRAIT_MULE 		= 2^6;
TRAIT_SPY 		= 2^7;
TRAIT_GREASE 	= 2^8;
TRAIT_SPEEDY 	= 2^9;
TRAIT_RUSSIAN	= 2^10;
TRAIT_CHINESE	= 2^11;
TRAIT_JAPANESE	= 2^12;
TRAIT_SPANISH	= 2^13;
TRAIT_FRENCH	= 2^14;
TRAIT_GERMAN	= 2^15;
TRAIT_ITALIAN	= 2^16;

TEAM_CITIZEN		= 1;
TEAM_COMBINE		= 2;
TEAM_OFFCOMBINE		= 3;
TEAM_STALKER 		= 4;
TEAM_VORTIGAUNT		= 5;
TEAM_OVERWATCH		= 6;
TEAM_UNCONNECTED	= 1001;

DONATION_CHAR_CREDITS 				= 1;
DONATION_CHAR_STATSTRENGTH 			= 2;
DONATION_CHAR_STATSPEED 			= 3;
DONATION_CHAR_STATTOUGHNESS			= 4;
DONATION_CHAR_STATAGILITY			= 5;
DONATION_CHAR_STATPERCEPTION		= 6;
DONATION_CHAR_STATAIM				= 7;
DONATION_CHAR_STATS					= 8;
DONATION_CHAR_MODEL					= 9;

DONATION_PLY_PROPLIMIT				= 1;
DONATION_PLY_RAGDOLLLIMIT			= 2;
DONATION_PLY_SCOREBOARDTITLE		= 3;
DONATION_PLY_SCOREBOARDTITLECOLOR	= 4;

MICROPHONE_BIG 		= 50;
MICROPHONE_SMALL 	= 56;

DRUG_BREEN 		= 1;
DRUG_MEDKIT 	= 2;
DRUG_VODKA 		= 3;
DRUG_ANTLION 	= 4;
DRUG_EXTRACT 	= 5;

BADGE_BETATEST	= 1;
BADGE_BETASCR	= 2;
BADGE_BIRTHDAY	= 4;

LOCATION_CITY = 1;
LOCATION_CANAL = 2;
LOCATION_OUTLANDS = 3;
LOCATION_COAST = 4;

GENDER_MALE = 1;
GENDER_FEMALE = 2;
GENDER_CP = 3;
GENDER_VORT = 4;
